spring.application.name=backend

easyparcel.api=${EASYPARCEL_API}
easyparcel.client-id=${EASYPARCEL_CLIENT_ID}
easyparcel.client-secret=${EASYPARCEL_CLIENT_SECRET}
easyparcel.redirect-uri=${EASYPARCEL_REDIRECT_URI}
easyparcel.token=${EASYPARCEL_TOKEN}
