spring.application.name=backend

google.client.id=934211844406-dmg5jps33o9v4js1qhp5qb7haqa5jd0k.apps.googleusercontent.com
google.client.secret=
google.redirect.uri=com.yiuernnn.mobile:/oauth

easyparcel.api=EP-4Gg5PhNZJ
easyparcel.client-id=2461e88d-479d-4ec1-a451-098cd9692ff0
easyparcel.client-secret=a5942e08-a6cf-41a2-af30-375738345a1e
easyparcel.redirect-uri=http://localhost:8080/easyparcel/callback
easyparcel.token=eyJhbGciOiJIUzI1NiJ9.eyJhcHAiOnsiY2xpZW50X2lkIjoiMjQ2MWU4OGQtNDc5ZC00ZWMxLWE0NTEtMDk4Y2Q5NjkyZmYwIn0sInVzZXIiOnsiaWQiOiJjYTU1ODlmNmE5M2JlNjk2ZWI2NDIyNTE0ODUxZTI0NFI4YzdCT3ZhN1VYalBleUlZblkycmc9PSIsImVhc3lfYWNjb3VudF9pZCI6IjZiNTI4OTY4LWE0Y2UtNDUwNi1iYjYwLTMxZGMyZjA2OGUwMCIsImFjY291bnRfaWQiOiI4MjkwNzkyIn0sImFjY291bnRfYXBwX3V1aWQiOiJkNTYxMzY2Mi01MzFlLTQ0YjMtODJmNy0yYjVlZTk1Y2U0ZDUiLCJpYXQiOjE3Nzk2NDYwOTQsImlzcyI6ImVhc3lwYXJjZWwiLCJhdWQiOiJlYXN5cGFyY2VsIiwiZXhwIjoxNzc5NjgyMDk0fQ.XV-Fa-NtmndWCxCbcreZhPvfxcksYJNXzFdLN2fJuyI
